language: node_js
node_js:
  - "6"
before_install:
  - npm install -g yarn
install:
  - yarn install
  - npm uninstall eslint-plugin-jsx-a11y
  - npm install eslint-plugin-jsx-a11y@2.2.3
script:
  - yarn lint
  - yarn test:cov
after_success:
  - yarn coveralls
